export enum SecretNames {
    PG_DATABASE = 'PG_DATABASE',
    CRYPTO_CONFIG = 'CRYPTO_CONFIG',
    SENDGRID_CONFIG = 'SENGRID_CONFIG',
    BFF_CLINICA_ROUTES = 'BFF_CLINICA_ROUTES',
    TICNOW_CONFIG = 'TICNOW_CONFIG',
    JWT_CONFIG = 'JWT_CONFIG',
    REGIONAL_CONFIG = 'REGIONAL_CONFIG',
}
